name: "Auto assign maintainer to issue"
on:
  issues:
    types: [opened]

permissions: {}

jobs:
  assign-maintainer:
    uses: grafana/k6/.github/workflows/issue-auto-assign.yml@5b725e8a6a52659b9aad111b3457621f2ea69af7  # v1.4.2
    permissions:
      issues: write